### ISSUE TITLE
pip returns `403 Client Error: SSL is required` error when building verifier image.

### ISSUE THREAD

**Issue by bartoszbetka** [golemfactory/concent-deployment#296] opened 2019-01-09 15:42 UTC
We use docker with blender image from dockerhub golemfactory/blender. The some changes in debian jessie libs cause error when we try install [requirements](https://github.com/golemfactory/golem/blob/b0.19/apps/rendering/resources/images/requirements.txt) for verifier. 

To reproduce problem:
```
python3 -m pip install --no-cache-dir --extra-index-url https://builds.golem.network opencv-python
Looking in indexes: https://pypi.org/simple, https://builds.golem.network
Collecting opencv-python
Could not install packages due to an EnvironmentError: 403 Client Error: SSL is required for url: http://pypi.python.org/simple/opencv-python/

**Comment by maaktweluit** [comment] 2019-01-09 16:18
I have seen this error before when using an older version of pip, could you check its version and/or try to upgrade it?

**Comment by cameel** [comment] 2019-01-09 17:48
@maaktweluit From what we found out so far, it seems to happen only on Debian Jessie (Stretch is fine). And only with the latest pip version (18.1).

We've run into it in the past too, when we first needed to handle the extra repository with dependencies for golem-messages. I think we worked around it by using `--find-links` instead of `--extra-index-url` back then in our requirements file that has `golem-messages` as a dependency. I don't know what the root cause is but we concluded that it would be best to just update the blender image to use the latest Debian instead of spending more time on solving this. I reported it later in https://github.com/golemfactory/golem/issues/3310.

So for now our workaround is to downgrade pip version used in this particular container to 18.0. But if you have any suggestions we can investigate more. At first I thought that maybe `--extra-index-url` makes `pip` use the default for `--index-url` which on old Debian might be the HTTP URL but that does not seem to be the case.

It's really weird because it works fine with HTTPS as long as you don't give it the `--extra-index-url` option with a HTTPS URL. Then, out of nowhere, it tries to access PyPI over HTTP.

**Comment by PaweuB** [comment] 2019-01-10 10:49
Pivotal:
https://www.pivotaltracker.com/story/show/163114619

**Comment by cameel** [comment] 2019-01-17 14:26
I'm reopening this because what we did was just a workaround. There's no proper solution yet. Turns out that this still happens on the latest Debian Stretch (see #310).

Since we have a workaround, this is not a high priority but we'll have to solve it eventually. It's not a good idea to keep using old `pip` indefinitely.

**Comment by PaweuB** [comment] 2019-01-17 14:51
Pivotal for workaround that has been done:
https://www.pivotaltracker.com/story/show/163296207

**Comment by cameel** [comment] 2019-01-18 16:46
@maaktweluit @bartoszbetka I have found the root cause of this problem. Golem's package registry (https://builds.golem.network) itself works over HTTPS but seems to have a HTTP redirect to PyPI for packages it does not host.

`pip` when installing for packages first checks all available versions in all the indexes. So first it gets the page at `https://pypi.org/simple/<package name>/`. If we specify `--extra-index-url`, it also goes to `https://builds.golem.network/simple/<package name>/`. For packages that exist there, e.g. `golem-messages` this returns the index page. But for ones that do not exist it results in a HTTP 302 redirect to `http://pypi.python.org/simple/<package name/` and then HTTP 403 because PyPI is not available over plain HTTP.

Try this:
``` bash
wget https://builds.golem.network/simple/appdirs/
```
```
--2019-01-18 17:30:25--  https://builds.golem.network/simple/appdirs/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving builds.golem.network (builds.golem.network)... 188.165.220.221
Connecting to builds.golem.network (builds.golem.network)|188.165.220.221|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://pypi.python.org/simple/appdirs/ [following]
--2019-01-18 17:30:26--  http://pypi.python.org/simple/appdirs/
Resolving pypi.python.org (pypi.python.org)... 151.101.112.223, 2a04:4e42:1b::223
Connecting to pypi.python.org (pypi.python.org)|151.101.112.223|:80... connected.
HTTP request sent, awaiting response... 403 SSL is required
2019-01-18 17:30:26 ERROR 403: SSL is required.
```

So this is something that needs to be fixed in Golem's infrastructure. I don't know about the older versions of pip but with 18.0 the redirect is not even necessary because pip check PyPI separately. The redirect, even if it worked, would only slow down the installation because of too many requests.

BTW, I'm not sure why downgrading to pip 18.0 even worked - because for me it doesn't work now. It did work when @bartoszbetka was building the container but for me, in a clear virtualenv in a Debian VM I get the same error no matter which version I use.

**Comment by cameel** [comment] 2019-01-21 15:28
@bartoszbetka https://github.com/golemfactory/golem/issues/3786 has been resolved. You can remove hard-coded pip version in our containers. Then we can close this issue.

**Closed** 2019-01-24 11:51 UTC
Labels: bug
